[build]
  command = "npm run build"
  publish = ".next"

[context.production.environment]
  NEXT_IGNORE_ESLINT = "1"
  PRISMA_GENERATE_SKIP_AUTOINSTALL = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
